### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by codepathreview** [lcam/codepath-android-todo#1]
Hello Leon, 

Thanks for submitting your pre-work but your current submission is incomplete. Your github repository does not appear to have any Android source code checked in or the source code appears incomplete. Please review the [submitting your prework guide](http://courses.codepath.com/snippets/intro_to_android/prework#heading-4-submitting-the-project) and [how to push code to a github repo](https://help.github.com/articles/create-a-repo/) and verify that your github repo has your latest Android source code.
Your application crashes at start with error " Java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codepath.simpletodo/com.codepath.simpletodo.MainActivity}: android.database.sqlite.SQLiteException: no such table: Task (code 1): , while compiling: Select \* from Task "

Please re-submit your project on your [application dashboard](https://apply.codepath.com/dashboard/) and reply back on this issue once that's completed.

**Comment by lcam** [comment]
Hello Codepath,

All of my code uploaded correctly onto Github at the time of submission.
Is the message about not seeing complete source code an auto-reply because
of the runtime error?  I'm not sure why you're receiving that SQLiteException.
The project builds and runs without a problem on my machine.  Please let me
know how I can help diagnose why the app crashes on your machine.

Thank you for your time,
Leon

**Comment by codepathreview** [comment]
Hello Leon, 
Looks great, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete a large number of extensions to your app already. Your project looks great. As you can probably tell, the extension tasks available on each project are the valuable learnings since they dive deeper into common real-world Android use cases. 

Be sure to take a look through our [organizing your source files guide](http://guides.codepath.com/android/Organizing-your-Source-Files#android-folder-structure) for tips on organizing your code as well.

Now that you've completed the pre-work, we'll be following up with you again shortly to outline the next steps in the admissions process.
